Trigger GitHub Actions on main

diff --git a/.github/workflows/cicd-workflow.yml b/.github/workflows/cicd-workflow.yml
--- a/.github/workflows/cicd-workflow.yml
+++ b/.github/workflows/cicd-workflow.yml
@@ -7,6 +7,7 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -29,7 +30,13 @@ jobs:
             --output text | tr -d '\r')
 
           echo "Latest task definition: $TASK_DEF_ARN"
-          echo "TASK_DEF_ARN=${TASK_DEF_ARN}" >> $GITHUB_ENV
+
+          if [ -z "$TASK_DEF_ARN" ]; then
+            echo "❌ Task definition ARN not found. Exiting..."
+            exit 1
+          fi
+
+          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
 
       - name: Deploy latest ECS task definition
         uses: aws-actions/amazon-ecs-deploy-task-definition@v1
